=== alxhoff/Datalog-API/datalog.xsd
<?xml version"1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    elementFormDefault="qualified">
    <!-- Types -->
    <xs:simpleType name="yearType">
        <xs:restriction base="xs:integer">
            <xs:minInvlusive value="2017"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:minInvlusive value="([a-z]*)@([a-z]*)"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- doc elements types-->
    
    <xs:element name="variable" type="xs:string"/>
    <xs:element name="constant" type="xs:string"/>

    <xs:complexType name="literal">
        <xs:sequence>
            <xs:element name="predicate"/>
            <xs:element name="terms">
                <xs:complexType>
                    <xs:element ref="variable|constant"/>
                    <xs:element ref="variable|constant"/>
                </xs:complexType>
            <xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fact">
        <xs:element name="head">
            <xs:element name="literal" type="literal"/>
    </xs:element>
    </xs:complexType>

    <xs:complexType name="rule">
        <xs:element name="head" type="literal"/>
        <xs:element name="body">
            <xs:complexType>
                <xs:element name="literal" type="literal"/>
                <xs:element name="literal" type="literal"/>
            </xs:complexType>
        </xs:element>
    </xs:complexType>
    
    <!-- Main doc elements -->
    <xs:element name="metadata">
        <xs:complexType>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="device">
                <xs:complexType>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="type" type="xs:string"/>
                    <xs:element name="manufacturer" type="xs:string"/>
                    <xs:element name="contact" type="emailType"/>
                    <xs:element name="model" type="xs:string"/>
                    <xs:element name="serial" type="xs:string"/>
                    <xs:element name="year" type="yearType"/>
                </xs:complexType>
            </xs:element>
        </xs:complexType>
    </xs:element>

    <xs:element name="mappings">
        <xs:element name="fact" type="fact" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="rule" type="rule" minOccurs="0" maxOccurs="unbounded"/>
    </xs:element>

    <!-- Doc structure -->
    <xs:element name="datalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="metadata" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="mappings" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== alxhoff/Datalog-API/bin/query_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<datalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datalog.xsd">
  <mappings>
  	<fact>
  		<head>
  			<literal>
  				<predicate>opc_Node</predicate>
  				<terms>
  					<constant>ns=1;i=288</constant>
  					<constant>UAObject</constant>
  				</terms>
  			</literal>
  		</head>
  	</fact>
  	<fact>
  		<head>
  			<literal>
  				<predicate>opc_UAObject</predicate>
  				<terms><constant>ns=1;i=288</constant>
  					<constant>EventNotifierTest1</constant></terms>
  			</literal>
  		</head>
  	</fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=289</constant>
            <constant>UAObject</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAObject</predicate>
          <terms><constant>ns=1;i=289</constant>
            <constant>EventNotifierTest2</constant></terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=56</constant>
            <constant>UAObject</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAObject</predicate>
          <terms><constant>ns=1;i=56</constant>
            <constant>EventNotifierTest3</constant></terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=104</constant>
            <constant>UAObject</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAObject</predicate>
          <terms><constant>ns=1;i=104</constant>
            <constant>EventNotifierTest4</constant></terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=290</constant>
            <constant>UAObject</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAObject</predicate>
          <terms><constant>ns=1;i=290</constant>
            <constant>EventNotifierTest5</constant></terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=55</constant>
            <constant>UAObjectType</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAObjectType</predicate>
          <terms><constant>ns=1;i=55</constant>
            <constant>IsAbstract1</constant></terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=105</constant>
            <constant>UAVariable</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAVariable</predicate>
          <terms><constant>ns=1;i=105</constant>
            <constant>TestValue1</constant>
            <constant>TestDataType1</constant>
            <constant>TestValueRank1</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=108</constant>
            <constant>UAVariable</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAVariable</predicate>
          <terms><constant>ns=1;i=108</constant>
            <constant>TestValue2</constant>
            <constant>TestDataType2</constant>
            <constant>TestValueRank2</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=291</constant>
            <constant>UAVariable</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAVariable</predicate>
          <terms><constant>ns=1;i=291</constant>
            <constant>TestValue3</constant>
            <constant>TestDataType3</constant>
            <constant>TestValueRank3</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Node</predicate>
          <terms>
            <constant>ns=1;i=295</constant>
            <constant>UAVariable</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_UAVariable</predicate>
          <terms><constant>ns=1;i=295</constant>
            <constant>TestValue4</constant>
            <constant>TestDataType4</constant>
            <constant>TestValueRank4</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=288</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=289</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=289</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=290</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=289</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=297</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=290</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=291</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=55</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=56</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=56</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=104</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=104</constant>
            <constant>HasComponent</constant>
            <constant>ns=1;i=105</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=288</constant>
            <constant>HasTypeDefinition</constant>
            <constant>ns=1;i=55</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=289</constant>
            <constant>HasTypeDefinition</constant>
            <constant>ns=1;i=73</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=295</constant>
            <constant>HasTypeDefinition</constant>
            <constant>ns=1;i=68</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=55</constant>
            <constant>HasTypeDefinition</constant>
            <constant>ns=1;i=56</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=108</constant>
            <constant>HasTypeDefinition</constant>
            <constant>ns=1;i=68</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=105</constant>
            <constant>HasProperty</constant>
            <constant>ns=1;i=108</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_Reference</predicate>
          <terms>
            <constant>ns=1;i=291</constant>
            <constant>HasProperty</constant>
            <constant>ns=1;i=295</constant>
          </terms>
        </literal>
      </head>
    </fact>
    <fact>
      <head>
        <literal>
          <predicate>opc_BaseNodeClass</predicate>
          <terms>
            <constant>ns=1;i=288</constant>
            <constant>nodeClass#1</constant>
            <constant>1:Boiler#1</constant>
